mode: train  # "train" or "eval"

data:
  dataset_name: ag_news
  batch_size: 64
  max_seq_len: 128
  val_split: 0.1

model:
  type: transformer  # dnn or transformer
  num_classes: 4
  dropout: 0.1 #0.3 for dnn
  embedding_dim: 128 #100 for dnn
  hidden_dim: 256 #for dnn
  num_heads: 4 #for transformer
  num_layers: 2 #for transformer

training:
  epochs: 15
  patience: 5
  lr: 0.0010
  weight_decay: 0.0001

misc:
  save_dir: "checkpoints"
  model_file: "saved_model.pt"
  vocab_file: "vocab.pkl"
  seed: 42
