# config/config.yaml

mode: train  # or "eval"

data:
  dataset_name: ag_news
  batch_size: 64
  max_seq_len: 128

model:
  type: dnn  # you can later switch to "lstm" or "transformer"
  embedding_dim: 100
  hidden_dim: 256
  dropout: 0.3
  num_classes: 4

training:
  epochs: 10
  lr: 0.001
  weight_decay: 0.0001

misc:
  save_path: "saved_model.pt"
  seed: 42
